#!/usr/bin/env bash
# transfer a file from our client to a server:
len() {
    ((l = 0))
    for item in $@; do
        ((l++))
    done
    return $l
}
len $@
if (($? < 3)); then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -i $4 $1 $3@$2:
fi
