#!/usr/bin/env bash
# load
sudo apt -y update
sudo apt -y upgrade
sudo apt -y install nginx
sudo chown -R ubuntu /var/www/
touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
sudo chown -R ubuntu /usr/share/nginx/
echo -e "Ceci n'est pas une page\n" > /usr/share/nginx/html/404.html
sudo sed -i "/^}$/i \ \n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/CSnotThatHard;\n\t\t# Am omar but you can call me dehao\n\t}\n" /etc/nginx/sites-available/default
sudo sed -i "/^}$/i \ \n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t\t# Omar did this\n\t}\n" /etc/nginx/sites-available/default
# ++++++++++++++++++++
sudo sed -i "/^}$/i \ \n\tadd_header X-Served-By $HOSTNAME;\t\n" /etc/nginx/sites-available/default
# ++++++++++++++++++++

sudo service nginx restart
