#!/usr/bin/env bash
# Block all incoming traffic but
# except the following TCP ports: 22 (SSH) 443 (HTTPS SSL) 80 (HTTP)

sudo apt -y update
sudo apt -y upgrade
sudo apt install ufw
sudo ufw reset
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
