#!/usr/bin/env bash
# Run Nginx as Nginx
pkill apache2
sed -i '/server_name _;/a \\n\tuser nginx;\n' /etc/nginx/sites-available/default
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
