#!/usr/bin/env bash
# Run Nginx as Nginx
sed -i '/server_name _;/a \\n\tuser nginx;\n' /etc/nginx/sites-available/default
sed -i 's/user www-data/user nginx/g' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx start
